export const PLACE_TYPES = [
  { value: 'accounting', label: 'Văn phòng kế toán' },
  { value: 'airport', label: 'Sân bay' },
  { value: 'amusement_park', label: 'Công viên giải trí' },
  { value: 'aquarium', label: 'Thủy cung' },
  { value: 'art_gallery', label: 'Triển lãm nghệ thuật' },
  { value: 'atm', label: 'Trạm ATM' },
  { value: 'bakery', label: 'Tiệm bánh' },
  { value: 'bank', label: 'Ngân hàng' },
  { value: 'bar', label: 'Quán bar' },
  { value: 'beer_garden', label: 'Quán nhậu' },
  { value: 'beauty_salon', label: 'Tiệm làm đẹp/thẩm mỹ' },
  { value: 'bicycle_store', label: 'Cửa hàng xe đạp' },
  { value: 'book_store', label: 'Hiệu sách' },
  { value: 'bowling_alley', label: 'Tiệm bowling' },
  { value: 'bus_station', label: 'Bến xe bus' },
  { value: 'cafe', label: 'Quán cà phê' },
  { value: 'campground', label: 'Khu cắm trại' },
  { value: 'car_dealer', label: 'Đại lý ô tô' },
  { value: 'car_rental', label: 'Cho thuê xe' },
  { value: 'car_repair', label: 'Sửa chữa ô tô' },
  { value: 'car_wash', label: 'Rửa xe' },
  { value: 'casino', label: 'Sòng bạc' },
  { value: 'cemetery', label: 'Nghĩa trang' },
  { value: 'church', label: 'Nhà thờ' },
  { value: 'city_hall', label: 'Tòa thị chính' },
  { value: 'clothing_store', label: 'Shop quần áo' },
  { value: 'convenience_store', label: 'Cửa hàng tiện lợi' },
  { value: 'courthouse', label: 'Tòa án' },
  { value: 'dentist', label: 'Nha sĩ' },
  { value: 'department_store', label: 'Cửa hàng bách hóa' },
  { value: 'doctor', label: 'Bác sĩ/Phòng khám' },
  { value: 'drugstore', label: 'Hiệu thuốc' },
  { value: 'electrician', label: 'Thợ điện' },
  { value: 'electronics_store', label: 'Cửa hàng điện máy' },
  { value: 'embassy', label: 'Đại sứ quán' },
  { value: 'fire_station', label: 'Trạm cứu hỏa' },
  { value: 'florist', label: 'Tiệm hoa' },
  { value: 'funeral_home', label: 'Dịch vụ tang lễ' },
  { value: 'furniture_store', label: 'Cửa hàng nội thất' },
  { value: 'gas_station', label: 'Trạm xăng' },
  { value: 'gym', label: 'Phòng tập gym' },
  { value: 'hair_care', label: 'Tiệm tóc' },
  { value: 'hardware_store', label: 'Cửa hàng kim khí' },
  { value: 'hindu_temple', label: 'Đền thờ' },
  { value: 'home_goods_store', label: 'Cửa hàng đồ gia dụng' },
  { value: 'hospital', label: 'Bệnh viện' },
  { value: 'insurance_agency', label: 'Đại lý bảo hiểm' },
  { value: 'jewelry_store', label: 'Tiệm trang sức' },
  { value: 'laundry', label: 'Tiệm giặt là' },
  { value: 'lawyer', label: 'Luật sư' },
  { value: 'library', label: 'Thư viện' },
  { value: 'light_rail_station', label: 'Ga tàu điện' },
  { value: 'liquor_store', label: 'Cửa hàng rượu' },
  { value: 'local_government_office', label: 'Văn phòng chính quyền' },
  { value: 'locksmith', label: 'Thợ khóa' },
  { value: 'lodging', label: 'Nhà nghỉ/Khách sạn' },
  { value: 'meal_delivery', label: 'Giao đồ ăn' },
  { value: 'meal_takeaway', label: 'Đồ ăn mang đi' },
  { value: 'mosque', label: 'Nhà thờ Hồi giáo' },
  { value: 'movie_rental', label: 'Cho thuê phim' },
  { value: 'movie_theater', label: 'Rạp chiếu phim' },
  { value: 'moving_company', label: 'Dịch vụ chuyển nhà' },
  { value: 'museum', label: 'Bảo tàng' },
  { value: 'night_club', label: 'Hộp đêm' },
  { value: 'painter', label: 'Thợ sơn' },
  { value: 'park', label: 'Công viên' },
  { value: 'parking', label: 'Bãi đỗ xe' },
  { value: 'pet_store', label: 'Cửa hàng thú cưng' },
  { value: 'pharmacy', label: 'Nhà thuốc' },
  { value: 'physiotherapist', label: 'Vật lý trị liệu' },
  { value: 'plumber', label: 'Thợ ống nước' },
  { value: 'police', label: 'Đồn cảnh sát' },
  { value: 'post_office', label: 'Bưu điện' },
  { value: 'primary_school', label: 'Trường tiểu học' },
  { value: 'real_estate_agency', label: 'Bất động sản' },
  { value: 'restaurant', label: 'Nhà hàng' },
  { value: 'roofing_contractor', label: 'Thợ làm mái' },
  { value: 'rv_park', label: 'Bãi đỗ xe lưu động' },
  { value: 'school', label: 'Trường học' },
  { value: 'secondary_school', label: 'Trường trung học' },
  { value: 'shoe_store', label: 'Cửa hàng giày' },
  { value: 'shopping_mall', label: 'Trung tâm thương mại' },
  { value: 'spa', label: 'Spa/Massage' },
  { value: 'stadium', label: 'Sân vận động' },
  { value: 'storage', label: 'Kho bãi' },
  { value: 'store', label: 'Cửa hàng bán lẻ' },
  { value: 'subway_station', label: 'Ga tàu điện ngầm' },
  { value: 'supermarket', label: 'Siêu thị' },
  { value: 'synagogue', label: 'Nhà nguyện Do Thái' },
  { value: 'taxi_stand', label: 'Điểm đón taxi' },
  { value: 'tourist_attraction', label: 'Điểm du lịch' },
  { value: 'train_station', label: 'Ga tàu hỏa' },
  { value: 'transit_station', label: 'Trạm trung chuyển' },
  { value: 'travel_agency', label: 'Đại lý du lịch' },
  { value: 'university', label: 'Trường đại học' },
  { value: 'veterinary_care', label: 'Thú y' },
  { value: 'zoo', label: 'Vườn thú' }
];
